---
- name: "{{ ct_zookeeper_task_prefix }} Persist data?"
  include_vars: persist_data.yml
  when: ct_zookeeper_persist_data|bool
- name: "{{ ct_zookeeper_task_prefix }} Create Zookeeper node"
  include_tasks: node.yml
  loop: "{{ ct_zookeeper_zookeeper_nodes }}"
  loop_control:
    loop_var: ct_zookeeper_node
  when: ct_zookeeper_node.host == inventory_hostname
...
